services:
  keycloak:
    build: .
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: db_admin
      KC_DB_PASSWORD: db_password
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_HOSTNAME: 0.0.0.0
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_FEATURES: organization
    command: >
      --http-enabled=true
      --hostname-strict=false
      --hostname=localhost

  db:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password
    volumes:
      - .data/postgresql:/var/lib/postgresql/data